# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='LexicalDensity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='PunctuationIndex',
            field=models.CharField(default='0', max_length=200, null=True, verbose_name='punctuation index'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ReadabilityIndex',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='center_of_gravity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cogX',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cogY',
            field=models.FloatField(default=0, null=True),
        ),
    ]
