# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160331_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='LexicalDensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='ReadabilityIndex',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
