# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160419_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='CompoundWord',
            field=models.BooleanField(default=False, verbose_name='complex word'),
        ),
    ]
