# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ComprehensionAnswer',
            new_name='Comprehension',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ComprehensionQuestion',
            new_name='Comprehension',
        ),
        migrations.AlterField(
            model_name='comprehension',
            name='ComprehensionTitle',
            field=models.CharField(max_length=100, unique=True, verbose_name='Comprehension Title'),
        ),
    ]
