# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='CompoundWord',
            field=models.BooleanField(default=False, verbose_name='complex word'),
        ),
        migrations.AlterField(
            model_name='question',
            name='LexicalDensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='PunctuationIndex',
            field=models.CharField(default='0', max_length=200, null=True, verbose_name='punctuation index'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QuestionTypeID',
            field=models.ManyToManyField(related_name='questiontypes', to='qa.QuestionType', verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ReadabilityIndex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='center_of_gravity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cogX',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cogY',
            field=models.FloatField(default=0, null=True),
        ),
    ]
