# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160309_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 9, 15, 53, 39, 151602, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='Comprehension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Comprehension', verbose_name='Comprehension'),
        ),
        migrations.AlterField(
            model_name='question',
            name='Comprehension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.Comprehension', verbose_name='comprehension'),
        ),
    ]
