# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20160411_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='AnswerTypeID',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Comprehension',
        ),
        migrations.RemoveField(
            model_name='patterns',
            name='AnswerTypeID',
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='CompoundWord',
            field=models.BooleanField(default=False, verbose_name='complex word'),
        ),
        migrations.AlterField(
            model_name='question',
            name='QuestionTypeID',
            field=models.ManyToManyField(related_name='questiontypes', to='qa.QuestionType', verbose_name='Question Type'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerType',
        ),
    ]
