# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20160425_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='LexicalDensity',
        ),
        migrations.RemoveField(
            model_name='question',
            name='PunctuationIndex',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ReadabilityIndex',
        ),
        migrations.RemoveField(
            model_name='question',
            name='center_of_gravity',
        ),
        migrations.RemoveField(
            model_name='question',
            name='cogX',
        ),
        migrations.RemoveField(
            model_name='question',
            name='cogY',
        ),
    ]
