# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_dictionary_comprehension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='Comprehension',
        ),
    ]
