# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_auto_20160309_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='StemmedWord',
            field=models.CharField(max_length=200, null=True, verbose_name='word'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='Word',
            field=models.CharField(default='none', max_length=200, unique=True, verbose_name='word'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='WordType',
            field=models.CharField(max_length=200, null=True, verbose_name='word type'),
        ),
    ]
