# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_auto_20160311_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='StemmedWord',
            field=models.CharField(max_length=200, null=True, verbose_name='stemmed word'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='Word',
            field=models.CharField(max_length=200, unique=True, verbose_name='word'),
        ),
    ]
