# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_auto_20160311_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='Word',
            field=models.CharField(default='none', max_length=200, verbose_name='word'),
        ),
    ]
