# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20160311_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(max_length=500, verbose_name='Question Text')),
                ('QuestionTagsOnly', models.CharField(blank=True, max_length=500, null=True, verbose_name='pos tags')),
                ('QuestionRemarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='remarks')),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('QuestionTypeID', models.ManyToManyField(to='qa.QuestionType', verbose_name='Question Type')),
            ],
        ),
    ]
