# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_independentquestion_questiontagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='independentquestion',
            name='QuestionSet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.IndependentQuestionSet', verbose_name='question set'),
        ),
    ]
