# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_auto_20160312_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='LexicalDensity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='PunctuationIndex',
            field=models.CharField(default='0', max_length=200, verbose_name='puncuation index'),
        ),
        migrations.AddField(
            model_name='question',
            name='ReadabilityIndex',
            field=models.FloatField(default=0),
        ),
    ]
