# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_auto_20160314_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='LexicalDensity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='PunctuationIndex',
            field=models.CharField(default='0', max_length=200, verbose_name='punctuation index'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ReadabilityIndex',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='LexicalDensity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='PunctuationIndex',
            field=models.CharField(default='0', max_length=200, verbose_name='punctuation index'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ReadabilityIndex',
            field=models.FloatField(),
        ),
    ]
