# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0017_auto_20160315_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='NamedEntity',
            field=models.BooleanField(default=False, verbose_name='named entity'),
        ),
    ]
