# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0018_auto_20160315_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionarySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
