# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0019_dictionaryset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='DictionarySet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qa.DictionarySet', verbose_name='dictionary set'),
            preserve_default=False,
        ),
    ]
