# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0020_dictionary_dictionaryset'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedEntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='NamedEntityTypeID',
            field=models.ManyToManyField(to='qa.NamedEntityType', verbose_name='named entity'),
        ),
    ]
