# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0021_auto_20160316_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='NamedEntityTypeID',
            field=models.ManyToManyField(blank=True, to='qa.NamedEntityType', verbose_name='named entity type'),
        ),
    ]
