# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0022_auto_20160316_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedentitytype',
            name='punjabi_name',
            field=models.CharField(default='\u0a30', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='namedentitytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
