# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0023_auto_20160316_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='CompoundWord',
            field=models.BooleanField(default=False, verbose_name='compoun word'),
        ),
    ]
