# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0024_dictionary_compoundword'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='QuestionTagged',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='pos tagged text'),
        ),
    ]
