# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0025_question_questiontagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='DictionarySet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.DictionarySet', verbose_name='dictionary set'),
        ),
    ]
