# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0026_auto_20160320_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='center_of_gravity',
            field=models.FloatField(default=0),
        ),
    ]
