# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0027_question_center_of_gravity'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cogX',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='cogY',
            field=models.FloatField(default=0),
        ),
    ]
