# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0028_auto_20160320_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='center_of_gravity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='cogX',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='cogY',
            field=models.FloatField(default=0),
        ),
    ]
